# NAME: Nevin Liang
# EMAIL: nliang868@g.ucla.edu
# ID: 705575353

lab4a: dist

clean:
	rm -f lab4a-705575353.tar.gz

dist: my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile
	tar -czf lab4a-705575353.tar.gz my_beaglebone.jpg connected.png copy.png \
		build_run.png git.png README Makefile
